spring:
    config:
        activate:
            on-profile: prod

springdoc:
    api-docs:
        enabled: false
    swagger-ui:
        enabled: false

logging:
    level:
        root: INFO
        ru.hvostid: INFO

management:
    endpoints:
        web:
            exposure:
                include: health

hvostid:
    cors:
        allowed-origins: ${HVOSTID_CORS_ALLOWED_ORIGINS:http://localhost}
