spring:
    config:
        activate:
            on-profile: prod
    flyway:
        locations: classpath:db/migration

springdoc:
    api-docs:
        enabled: false
    swagger-ui:
        enabled: false

logging:
    level:
        ru.hvostid: INFO
