rule_files:
    - alerts.yml
evaluation_interval: 15s
tests:
    - interval: 15s
      input_series:
          - series: 'up{job="hvostid", service="passport-service", instance="passport-service:8083"}'
            values: '1 0 0 0 0 0 0 0 0'
      alert_rule_test:
          - eval_time: 2m
            alertname: HvostidServiceDown
            exp_alerts:
                - exp_labels:
                      job: hvostid
                      service: passport-service
                      instance: passport-service:8083
                      severity: critical
                  exp_annotations:
                      summary: 'Service passport-service cannot be scraped'
